# Generated by Django 4.2.7 on 2023-11-26 22:22

import datetime
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hotel_name', models.CharField(help_text='Enter field name', max_length=50, verbose_name='Hotels name')),
                ('qstars', models.CharField(max_length=50, verbose_name='How many stars')),
                ('qfloor', models.IntegerField(verbose_name='Number of froors')),
                ('qroom', models.IntegerField(verbose_name='How many rooms')),
                ('hotel_Main_Img', models.ImageField(upload_to='images/')),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.UUIDField(default=uuid.UUID, help_text='Unique ID for this person', primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=50, verbose_name='First name')),
                ('last_name', models.CharField(max_length=50, verbose_name='Last name')),
                ('telefon', models.CharField(max_length=50, verbose_name='Telefon')),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num', models.IntegerField(verbose_name='Room number')),
                ('room_name', models.CharField(max_length=50, verbose_name='Room name')),
                ('view_from_the_window', models.CharField(max_length=50, verbose_name='View from the window')),
                ('price', models.CharField(help_text='Enter field name', max_length=50, verbose_name='Price')),
                ('free', models.CharField(help_text='Enter field name', max_length=50, verbose_name='Free')),
                ('photo', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('order_num', models.IntegerField(verbose_name='Orders number')),
                ('id', models.UUIDField(default=uuid.UUID, help_text='Unique ID for this order', primary_key=True, serialize=False)),
                ('date1', models.DateTimeField(default=datetime.datetime.now)),
                ('date2', models.DateTimeField()),
                ('when_was_created', models.DateTimeField(default=datetime.datetime.now)),
                ('Room', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='hotel.room')),
                ('person', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='hotel.person')),
            ],
        ),
    ]
